# .pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
  - id: check-byte-order-marker
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-executables-have-shebangs
  - id: check-ast
  - id: check-docstring-first
  - id: check-json
  - id: pretty-format-json
    args: ['--autofix', '--no-ensure-ascii']

- repo: git@github.com:PyCQA/isort.git
  rev: 5.12.0
  hooks:
    - id: isort

- repo: git@github.com:psf/black.git
  rev: 23.3.0
  hooks:
    - id: black
      language_version: python3

- repo: git@github.com:PyCQA/autoflake.git
  rev: v2.1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
